### ISSUE TITLE
KUBECONFIG env variable not being used

### ISSUE THREAD

**Issue by luizfelipefb** [kdash-rs/kdash#314]
**Describe the bug**
KUBECONFIG environment variable indicating where my config files are is not being used

**To Reproduce**
Steps to reproduce the behavior or a screencast
1. create multiple config files for multiple clusters and do not save ANY of them in ~/.kube/config
2. use KUBECONFIG to map all the files as: `~/.kube/config1:~/.kube/config1:~/some/other/path/configfile`
3. start kdash

**Expected behavior**
To have the same view as using a single config file in the default locations

**Screenshots**
![image](https://user-images.githubusercontent.com/3042811/234748150-93e608ae-adaa-4558-a92c-4f17408f7fff.png)

**Desktop (please complete the following information):**
 - OS and OS version: Windows 11
 - Terminal name and version: WSL with kali-linux
 - Shell name and version: zhs
 - Kubectl Client Version: 1.27.1
 - Kubectl Server Version: several
 - KDash version: 0.3.6

**Additional context**
N/A

**Comment by clux** [comment]
Was curious and had a look here because kube supports this. kdash calls ultimately look sensible:

- [kdash uses Kubeconfig::read](https://github.com/kdash-rs/kdash/blob/643d2e01e2cc8f7d46da1c219eba0dc49de6fa50/src/network/kube_api.rs#L56) in kube_api module
- [Kubeconfig::read](https://docs.rs/kube-client/0.83.0/src/kube_client/config/file_config.rs.html#384-416) merges all files found from the standard KUBECONFIG evar
- [kdash uses Config::from_kubeconfig](https://github.com/kdash-rs/kdash/blob/643d2e01e2cc8f7d46da1c219eba0dc49de6fa50/src/network/mod.rs#L63-L75) in network mod
- [Config::from_kubeconfig](https://docs.rs/kube/latest/kube/struct.Config.html#method.from_kubeconfig) will ultimately call `Kubeconfig::read` and pick the one matching kdash's saved context

...so tried with two k3d clusters with `KUBECONFIG="/home/clux/.kube/k3d:/home/clux/.kube/k3dmain"` and this totally works.
C swap clusters, both contexts show up (taking some time to switch contexts), and then seeing different pods

**Comment by clux** [comment]
Think the problem here is that you're referencing `~` in the `KUBECONFIG` string (which also doesn't work for me).
I'd use a full path, as using `KUBECONFIG="~/.kube/k3d:~/.kube/k3dmain" kubectl config get-contexts` does not work either so it's not just a kube-rs thing.

**Comment by deepu105** [comment]
Thank you @clux and yes it indeed seems like issue with `~`
