### ISSUE TITLE
kdash reacts to key-down and key-up events and jumps two records at the time

### ISSUE THREAD

**Issue by ppasieka** [kdash-rs/kdash#390]
**Describe the bug**
Attempt to navigate through any resource lists (pods, services, etc.) is hindered because the kdash reacts to key-down and key-up events. This results in the selection bar moving two rows at a time.

**To Reproduce**
Open kdash and navigate with j,k or arrow up/down

**Expected behavior**
Pressing navigational buttons (j, k) or (arrow up/down) should move one row at a time

**Screenshots**

**Desktop (please complete the following information):**
 - OS and OS version: Windows 10
 - Terminal name and version Windows terminal 1.17.11461.0
 - Shell name and version PowerShell 7.3.7
 - Kubectl Client Version v1.25.6
 - Kubectl Server Version v1.25.6
 - KDash version 0.4.4

**Comment by deepu105** [comment]
Probbaly is happening only on Windows as I dont see it on Linux. I would have to check but will take time

**Comment by deepu105** [comment]
any help to debug would be appreciated as well

**Comment by tired-old-man** [comment]
The problem is with changes in _crossterm_ library.
They introduced the **kind** to KeyEvent. It can have two values: Press and Release.

https://github.com/crossterm-rs/crossterm/pull/745
https://github.com/crossterm-rs/crossterm/commit/318f810a39a7d45af2068eb97a255cdfa18282e8

Since you upgraded the _crossterm_ library in version 0.3.7 this begin to happen.

You can see the same issue on _ratatui_.
https://github.com/ratatui-org/ratatui/issues/347

The suggestion is to check for key press kind:
> To fix this, check KeyEvent.kind == KeyEventKind.Press (on windows).

I'm not sure if it is that simple of a fix and how/will it affect other platforms.

**Comment by deepu105** [comment]
Thank you @tired-old-man
