### ISSUE TITLE
TODO - More resources to add

### ISSUE THREAD

**Issue by deepu105** [kdash-rs/kdash#44]
Workloads

- [x] Pods
- [x] Deployments
- [x] Replica sets
- [x] Stateful sets
- [x] Jobs #35 
- [x] Cron Jobs #45
- [x] Daemon sets #34 
- [x] Replication Controllers #46

Service

- [x] Services
- [x] Ingresses #47

Config/Storage

- [x] Config Maps
- [x] Secrets #48
- [x] Persistent Volume Claims #49
- [x] Storage classes #50

Cluster

- [x] Nodes
- [x] Namespaces
- [x] Cluster roles #51
- [x] Cluster role bindings #52
- [x] Network policies #53
- [x] Persistent volumes #54
- [x] Role bindings #55
- [x] Roles #56
- [x] Service accounts #57

**Comment by genofire** [comment]
A Generic view would be nice - based on CRDs e.g.
  - prometheus-operator: Prometheus,ServiceMonitor,PodMonitor, PrometheusRule, alertmanager,alertmanagerConfig
  - logging-operator: ClusterFlow,Flow,ClusterOutput,Output
  - fluxcd: GitRepository,HelmRepostory, Kustomize, HelmRelease
  - cert-manager: ClusterIssuer, Issuer, CertificateRequest, Request, Challanges
  - traefik: Middleware, IngressRoute
  - many more

**Comment by deepu105** [comment]
@genofire Yes would be nice but the initial infra for that probably would need some refactoring of the current codebase and unfortunately, I don't have enough time for that. If you or someone else wanna take a shot, I'll welcome it.

**Comment by deepu105** [comment]
@clux do you think it is feasible to get all the resources on the cluster using `api-resources` and then iterate through them and build `kube::core::DynamicObject` using the `Api::all_with` method and `GroupVersionKind` or something similar? I tried to play around with that but my Rust foo is not good enough it seems and got stuck at type mismatch and complex trait definitions

**Comment by clux** [comment]
..should is possible for you to display arbitrary dynamic resources, yep. have enough on my plate atm, but can offer some points:

1. `KubeResource` impls like [this](https://github.com/kdash-rs/kdash/blob/fee3d4be01e220a74268c63d2dd02f5dd9b8a924/src/app/secrets.rs#L29-L33) should be easy enough to replace in, probably something like:

```rust
struct DynamicObjectWrapper(DynamicObject)
impl KubeResource<Value> for DynamicObjectWrapper {
  fn get_k8s_obj(&self) -> &Value {
    &self.0.data
  }
}
```

2. you'd have to keep around discovery information for the types you wanted to show (or fully constructed `Api` objects), because you have these generic helpers to fetch that relies on `DynamicType: Default` in https://github.com/kdash-rs/kdash/blob/fee3d4be01e220a74268c63d2dd02f5dd9b8a924/src/network/kube_api.rs#L364-L423 and this wouldn't work with discovered types (since they don't have a manually constructed `DynamicType`). These are usually kept in examples as `ar`. See https://github.com/kube-rs/kube/blob/main/examples/dynamic_api.rs . Might be easiest to keep around fully constructed `Api` objects from discovery and look those up at runtime instead.

3. you won't have a sensible thing to use to display columns easily in the ui. you'd have to cross reference with the crd schema and look at [printer columns](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns) if you wanted to do this, which means you'd have to cache crds in the app, but that's probably not a big deal

4. `kube::discovery` can be configured to exclude the common types you've already implemented. meaning you shouldn't need to run into duplicates from discovery with your catch-all dynamic, and you'd speed up the process a bit

5. discovery takes a little bit of time (the api requires a lot of iteration). caching the discovery result would be better for a snappy CLI. there's an [open issue for this in kube](https://github.com/kube-rs/kube/issues/1021), but no one has really volunteered for it.

**Comment by deepu105** [comment]
@clux Thanks for the info 🙏 . Its really helpful. I'll try to cook something up based on this and see how far I get

**Comment by clux** [comment]
Hey, nice. That was quick! Code wise looks very sensible to me from a quick scan.

Minor point; you might be able to make the discovery exclusion a little less hard codey by doing  https://docs.rs/kube/latest/kube/discovery/struct.Discovery.html#method.exclude then giving it the `CORE_GROUP`, plus the main other other groups that you definitely specialise (authorization, apps, etc). Then you won't even ask the api to discover these, plus you'll have a clearer delineation boundary.

**Comment by deepu105** [comment]
Thanks for taking a look @clux appreciate that. I did try the exclude but wasn't working for the core group. What exactly is the key for that?

**Comment by deepu105** [comment]
oh and another reason `exclude` might not work is that not all kinds from a group is implemented so excluding by group will also remove the Kinds I actually want to load :(

**Comment by clux** [comment]
Ah, if you need to do it more granularly than by group then you're not saving api requests anyway so you may as well do the filtering you are already doing in that case.
